### PR TITLE
Merge main to live

### PR DESCRIPTION
**Pull request by shawnwang-w**
Including [[SEO][Rollout Monikered Canonical]Add URL moniker](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/commit/3d23e28194a5616575a3928cc28cd58e99ff8e1e)

### CODE REVIEW

**Comment by lindalu-MSFT** [comment]
Docs Build status updates of commit _[ea41c5d](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/commits/ea41c5d224b1397f11a3207f0a21e177154c2b8b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-862ff1fa)

<a id="862ff1fa"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit ea41c5d224b1397f11a3207f0a21e177154c2b8b in branch main of repository https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet into branch live (commit 58e157a652be04ef3255490a444c868d5132ad91). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/bf838749-b0ff-ddab-1f45-03d674adc109/202209140124154466-86/BuildReport?accessString=50b00d31e4b826371afae31ad7298b7ed65ac12f95defd5796ff2852eed30df2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/bf838749-b0ff-ddab-1f45-03d674adc109?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by TianqiZhang** [comment]
@lindalu-MSFT could you please help to take a look? It seems that there's conflict merging from main to live.

**Comment by lindalu-MSFT** [comment]
Hi, traveling now but can check and resolve this evening. Thanks for letting me know!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by TianqiZhang — APPROVED** [review]

**Comment by TianqiZhang** [comment]
@lindalu-MSFT we'd appreciate it if you could help take a look at this PR.

**Comment by lindalu-MSFT** [comment]
Docs Build status updates of commit _[5fc0f57](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/commits/5fc0f578241b929f24b8b220d4c2ee117ee71a62)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint-server/docfx.json](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/lindalu-fix-merge-error/sharepoint-server/docfx.json) | :warning:Warning | | [Details](#user-content-dc26991d7d06712cd1a8bb38c5fa1677-eadd17ab)
[sharepoint-server/xml/Microsoft.SharePoint.Taxonomy/Term.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/lindalu-fix-merge-error/sharepoint-server/xml/Microsoft.SharePoint.Taxonomy/Term.xml) | :warning:Warning | | [Details](#user-content-ed6fb4809ffa8dc5620c3a4be64c1a05-eadd17ab)
[.openpublishing.publish.config.json](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/lindalu-fix-merge-error/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

<a id="dc26991d7d06712cd1a8bb38c5fa1677-eadd17ab"></a>
### [sharepoint-server/docfx.json](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/lindalu-fix-merge-error/sharepoint-server/docfx.json)
 - **Line 50, Column 28**: **[Warning: ms-prod-technology-invalid - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.technology': 'sdk' is not valid with 'ms.prod' value 'sharepoint'.`````

<a id="ed6fb4809ffa8dc5620c3a4be64c1a05-eadd17ab"></a>
### [sharepoint-server/xml/Microsoft.SharePoint.Taxonomy/Term.xml](https://github.com/SharePoint/sp-dev-docs-2013-server-ref-dotnet/blob/lindalu-fix-merge-error/sharepoint-server/xml/Microsoft.SharePoint.Taxonomy/Term.xml)
 - **Line 0, Column 0**: **[Warning: xref-not-found]** `````Cross reference not found: 'Microsoft.SharePoiint.Taxonomy.Term'.`````
 - **Line 0, Column 0**: **[Warning: xref-not-found]** `````Cross reference not found: 'Microsoft.SharePoint.Taxoomy.Term'.`````
 - **Line 0, Column 0**: **[Warning: xref-not-found]** `````Cross reference not found: 'Microsoft.SharePoint.TermStore'.`````
 - **Line 0, Column 0**: **[Warning: xref-not-found]** `````Cross reference not found: 'Microsoft.SharePoint.Term'.`````
 - **Line 0, Column 0**: **[Warning: xref-not-found]** `````Cross reference not found: 'Microsoft.SharePoint.Taxonomy.TaxonomySession.KeywordTermSet'.`````
 - **Line 0, Column 0**: **[Warning: xref-not-found]** `````Cross reference not found: 'Microsoft.SharePoint.Term'.`````
 - **Line 0, Column 0**: **[Warning: xref-not-found]** `````Cross reference not found: 'Microsoft.SharePoint.Taxonomy.TermSetItem.CreateTerm'.`````
 - **Line 0, Column 0**: **[Warning: xref-not-found]** `````Cross reference not found: 'Microsoft.SharePoint.Taxonomy.TermStore.GetTerm'.`````
 - **Line 0, Column 0**: **[Warning: xref-not-found]** `````Cross reference not found: 'Microsoft.SharePoint.Taxonomy.Term.Move(TermSet)'.`````
 - **Line 0, Column 0**: **[Warning: xref-not-found]** `````Cross reference not found: 'Microsoft.SharePoint.TaxonomyTerm.Move(T:Microsoft.SharePoint.Taxonomy.Term)'.`````
 - **Line 0, Column 0**: **[Warning: xref-not-found]** `````Cross reference not found: 'Microsoft.Sharepoint.Taxonomy.TermSet'.`````
 - **Line 0, Column 0**: **[Warning: xref-not-found]** `````Cross reference not found: 'Microsoft.SharePoint.Taxonomy.Term.Merge'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/bf838749-b0ff-ddab-1f45-03d674adc109/202209261901540698-86/BuildReport?accessString=ba210f9c0d753a3ecc0e18f4722bdec0db18b3f5f97b8731a662e18b2b381641).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/bf838749-b0ff-ddab-1f45-03d674adc109?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by lindalu-MSFT** [comment]
@TianqiZhang Fixed and merged

**Pull request merged**
